# Generated by Django 3.0.8 on 2020-08-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200805_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
