# Generated by Django 3.0.8 on 2020-08-06 13:02

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='yt_video',
            field=embed_video.fields.EmbedVideoField(blank=True, max_length=140),
        ),
    ]
