# Generated by Django 2.2 on 2020-08-13 10:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200812_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_3',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
