# Generated by Django 2.2 on 2020-08-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200816_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
