# Generated by Django 2.2 on 2020-08-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_newsletter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
